In [1]:
from platform import python_version
print(f'Python version: {python_version()}')

Python version: 3.11.5


In [2]:
%pip install -q -U watermark

Note: you may need to restart the kernel to use updated packages.


# Estruturas de dados Numpy

In [2]:
import numpy as np

## Array

In [4]:
# criando um array unidimensional
array1 = np.array([10,20,30,40])

In [5]:
print(array1)

[10 20 30 40]


In [6]:
# verificando o formato do array
array1.shape

(4,)

In [7]:
# verificando a quantidade de dimensões do array
array1.ndim

1

In [8]:
# criando um array bi-dimensional
array2 = np.array([[100, 83, 15],  [42, 78, 0]])

In [9]:
print(array2)

[[100  83  15]
 [ 42  78   0]]


In [10]:
array2.shape

(2, 3)

In [11]:
array2.ndim

2

Na caralha do Python, tudo é objeto, isso implica que:
- cada objeto possui métodos (ações). Exemplo array2.max()
- cada objeto possui propriedades. Exemplo array2.ndim

Reparou a diferença? Quando é um método, uma ação, termina com (). Quando é uma propriedade termina sem nada.

In [12]:
array2.max()

100

In [13]:
array2.ndim

2

### Arange

In [14]:
array3 = np.arange(15)

In [15]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
array4 = np.arange(0,15,3)  #cria de 0 a (15-1) indo de 3 em 3
array4

array([ 0,  3,  6,  9, 12])

### Linspace
a quantidade de itens em um array igualmente espaçado pelo intervalo informado

In [17]:
array5 = np.linspace(0,3,4) # cria um array com 4 pontos começando em 0 e terminando em 3
array5

array([0., 1., 2., 3.])

In [18]:
array5a = np.linspace(0,10,10) # cria um array com 10 pontos começando em 0 e terminando em 10
array5a

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [19]:
array5b = np.linspace(1,10,10) #cria um array com 10 pontos começando em 1 e terminando em 10
array5b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Zeros
cria um array de zeros

In [20]:
array6 = np.zeros((10,8)) #cria um array com 10 elementos e com 8 itens em cada elemento
array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

### Ones

In [21]:
array7 = np.ones((2,3,2), dtype=int)
array7

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

### Eye
Cria uma matriz identidade (matriz com a diagonal com valores 1)

In [22]:
array8 = np.eye(3)
array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Diag
cria uma matriz com 0 e a diagonal com os valores indicados

In [23]:
array9 = np.diag((2,1,4,6))
array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### Random.rand
cria uma matriz com valores randômicos

In [24]:
array10 = np.random.rand(5) #crio 5 valores randômicos. A cada execução haverá valores novos
array10

array([0.00988112, 0.86677723, 0.82983439, 0.2143716 , 0.86374548])

In [25]:
np.random.seed(100) # travo os valores randômicos. A cada execução os valores serão os mesmos
array10a = np.random.rand(5)
array10a

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

### randn
Gera valores aleatórios com distribuição normal (Gaussian)

In [26]:
array11 = np.random.randn(5)
array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

### Empty
Cria um array vazio

In [27]:
array12 = np.empty((3,2))
array12

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.37961438e-306],
       [1.89146896e-307, 7.56571288e-307]])

### Tile
Multiplica o array pelo valor informado (cria cópias do array dentro do array)

In [28]:
arrayTile = np.array([1,2,3])
arrayTile

array([1, 2, 3])

In [29]:
np.tile(arrayTile, 2) #pegou o arrayTile e duplicou ele dentro dele mesmo

array([1, 2, 3, 1, 2, 3])

In [30]:
np.tile(arrayTile, (3,5,3)) #pegou o array tile, triplicou ele dentro dele mesmo, pegou o resultado e criou 5 dimensões, pegou o resultado e criou mais 3 dimensões

array([[[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]]])

### Definindo o tipo de dado do array

In [31]:
array13 = np.array([1,2,3], dtype=float)
array13

array([1., 2., 3.])

In [32]:
array13a = np.empty(5, dtype=int)
array13a

array([  15732993, -267321087,  285278472,   16842992,   16838673])

### Operações com Arrays

In [33]:
# multiplicando todos os elementos de um array
array19 = np.arange(0,30) * 5
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [34]:
# elevando os elementos de um array a uma potência
array20 = np.arange(5) ** 4
array20

array([  0,   1,  16,  81, 256], dtype=int32)

In [35]:
# Somando um número a cada elemento de array
array21 = np.arange(5) + 10
array21

array([10, 11, 12, 13, 14])

In [36]:
# Subtração de arrays
array22 = array21 - array20
array22

array([  10,   10,   -4,  -68, -242])

In [37]:
# Para operações elementares é necessário que todos os arrays tenham a mesma quantidade de elementos
array23 = array19 - array21
array23

ValueError: operands could not be broadcast together with shapes (30,) (5,) 

In [38]:
# Comparando logicamente dois arrays
array22 > array21

array([False, False, False, False, False])

### Indexação de arrays

In [42]:
# criando um array
array23 = np.arange(5)
array23

array([0, 1, 2, 3, 4])

In [40]:
# chamando o primeiro elemento do array
array23[0]

0

In [56]:
array24 = np.array([[190,290,490,],[129,458,567],[761,902,346]])
array24

array([[190, 290, 490],
       [129, 458, 567],
       [761, 902, 346]])

In [45]:
# Retorna os elementos do index 2 de linhas da matriz
array24[2]

array([761, 902, 346])

In [52]:
# Retorna os elementos do index 2 de linhas da matriz - modo alternatico
array24[2,]

array([761, 902, 346])

In [54]:
# Retorna todas as linhas da segunda coluna da matriz
array24[:,1]

array([290, 458, 902])

In [53]:
array24[2,1]

902

In [57]:
# atribuir um valor ao item da matriz
array24[1,1] = 99999
array24

array([[  190,   290,   490],
       [  129, 99999,   567],
       [  761,   902,   346]])

### Slicing de array

In [8]:
array25 = np.arange(50) * 2
array25

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
# quero pegar do 5º ao 10º índice, saltando de 2 em 2
array25[5:10:2]

array([10, 14, 18])

In [13]:
# retorna os valores até o índice 4
array25[:4] # o índice 4 não entra na lista pois o método é exclusico com o índice final

array([0, 2, 4, 6])

In [14]:
# retorna os valores a partir do indice 4
array25[4:] # o índice 4 entra na lista pois o método é inclusivo com o indice inicial

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40,
       42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74,
       76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [15]:
# retorna todos os itens a partir de zero, pulando de 3 em 3
array25[::3]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [16]:
# modificar itens de um array usando slicing
array25[:3] = 1
array25

array([ 1,  1,  1,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
# modificar um array com partes de outro array
array25[45:] = [2,2,2,9,2]
array25

array([ 1,  1,  1,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88,  2,  2,  2,  9,  2])

In [20]:
array25[10:15] = np.ones(5)
array25

array([ 1,  1,  1,  6,  8, 10, 12, 14, 16, 18,  1,  1,  1,  1,  1, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88,  2,  2,  2,  9,  2])

In [21]:
array25[16:30:3] = 999
array25

array([  1,   1,   1,   6,   8,  10,  12,  14,  16,  18,   1,   1,   1,
         1,   1,  30, 999,  34,  36, 999,  40,  42, 999,  46,  48, 999,
        52,  54, 999,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,   2,   2,   2,   9,   2])

### Subset de Arrays

In [23]:
array26 = array25[::2]
array26

array([  1,   1,   8,  12,  16,   1,   1,   1, 999,  36,  40, 999,  48,
        52, 999,  60,  64,  68,  72,  76,  80,  84,  88,   2,   9])

### Cópias de Arrays com np.copy

In [25]:
array27 = array26.copy()
array27

array([  1,   1,   8,  12,  16,   1,   1,   1, 999,  36,  40, 999,  48,
        52, 999,  60,  64,  68,  72,  76,  80,  84,  88,   2,   9])

### Transposição e Reshaping de Arrays

In [26]:
array28 = np.array([[190,290,490,],[129,458,567],[761,902,346]])
array28

array([[190, 290, 490],
       [129, 458, 567],
       [761, 902, 346]])

In [27]:
array28.T

array([[190, 129, 761],
       [290, 458, 902],
       [490, 567, 346]])

In [28]:
np.transpose(array28)

array([[190, 129, 761],
       [290, 458, 902],
       [490, 567, 346]])

### Broadcasting

In [34]:
array29 = np.array([[33,34,35]])
array29

array([[33, 34, 35]])

In [35]:
array29.T

array([[33],
       [34],
       [35]])

In [37]:
array29.T + array29

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])